### ISSUE TITLE
taskbar iconをクリックしても青くなるだけ

### ISSUE THREAD

**Issue by yut148** [nekobato/Polidium#7]
ファイル選択出来ない。。
メニューバーなのでこの事象をスクリーンショットに撮れないです。
本来はファイラーが表示されるのですね。
どこにも見えないです。

**Comment by nekobato** [comment]
packeage版ならば、

- HTML描画が更新されない
 - 画面をスワイプすると治る

という事象を確認しています。
他の事象はなんともわかりません。
次のバージョンでは描画の不安定さを修正しているので、そちらで副作用として治るかもしれません。

**Comment by yut148** [comment]
ビルドされているこちらは動作しました。
Polidium-darwin-x64.zip
